version: '3'

services:
  frontend:
    build: ./frontend
    container_name: project-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - project-docker-network


  api:
    build: ./api
    container_name: project-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://project-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - project-docker-network


  auth:
    build: ./auth
    container_name: project-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://project-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - project-docker-network


  api_db:
    image: mongo:latest
    container_name: project-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - project-docker-network


  auth_db:
    image: mongo:latest
    container_name: project-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - project-docker-network


  nginx:
    image: nginx:stable-alpine
    container_name: project-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - project-docker-network

volumes:
    mongodb_api:
    mongodb_auth:

networks:
  project-docker-network:
    driver: bridge
