version: '3'

services:
  frontend:
    build: ./frontend
    container_name: project-frontend
    command: serve -s build -l 3000
    restart: unless-stopped

  api:
    build: ./api
    container_name: project-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://project-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: project-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://project-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - auth_db


  api_db:
    image: mongo:latest
    container_name: project-api-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: project-auth-db
    volumes:
      - mongodb_auth:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: project-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend




volumes:
    mongodb_api:
    mongodb_auth:
